//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThuongMaiDienTu_DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        public int MaDG { get; set; }
        public int MaKH { get; set; }
        public int MaSP { get; set; }
        public int MaHD { get; set; }
        public int SoSao { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayDG { get; set; }
    
        public virtual CT_HOADON CT_HOADON { get; set; }
        public virtual NGUOIDUNG NGUOIDUNG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
